-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Github.Object.DeleteProjectCardPayload exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Github.Object
import Github.Interface
import Github.Union
import Github.Scalar
import Github.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Github.Object.DeleteProjectCardPayload
selection constructor =
    Object.selection constructor
{-| A unique identifier for the client performing the mutation.
-}
clientMutationId : Field (Maybe String) Github.Object.DeleteProjectCardPayload
clientMutationId =
      Object.fieldDecoder "clientMutationId" [] (Decode.string |> Decode.nullable)


{-| The column the deleted card was in.

**Upcoming Change on 2019-01-01 UTC**
**Description:** Type for `column` will change from `ProjectColumn!` to `ProjectColumn`.
**Reason:** In preparation for an upcoming change to the way we report mutation errors, non-nullable payload fields are becoming nullable.

-}
column : SelectionSet decodesTo Github.Object.ProjectColumn -> Field decodesTo Github.Object.DeleteProjectCardPayload
column object_ =
      Object.selectionField "column" [] (object_) (identity)


{-| The deleted card ID.

**Upcoming Change on 2019-01-01 UTC**
**Description:** Type for `deletedCardId` will change from `ID!` to `ID`.
**Reason:** In preparation for an upcoming change to the way we report mutation errors, non-nullable payload fields are becoming nullable.

-}
deletedCardId : Field Github.Scalar.Id Github.Object.DeleteProjectCardPayload
deletedCardId =
      Object.fieldDecoder "deletedCardId" [] (Object.scalarDecoder |> Decode.map Github.Scalar.Id)
