-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Github.Object.GitHubMetadata exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Github.Object
import Github.Interface
import Github.Union
import Github.Scalar
import Github.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Github.Object.GitHubMetadata
selection constructor =
    Object.selection constructor
{-| Returns a String that's a SHA of `github-services`
-}
gitHubServicesSha : Field Github.Scalar.GitObjectID Github.Object.GitHubMetadata
gitHubServicesSha =
      Object.fieldDecoder "gitHubServicesSha" [] (Object.scalarDecoder |> Decode.map Github.Scalar.GitObjectID)


{-| IP addresses that users connect to for git operations
-}
gitIpAddresses : Field (Maybe (List String)) Github.Object.GitHubMetadata
gitIpAddresses =
      Object.fieldDecoder "gitIpAddresses" [] (Decode.string |> Decode.list |> Decode.nullable)


{-| IP addresses that service hooks are sent from
-}
hookIpAddresses : Field (Maybe (List String)) Github.Object.GitHubMetadata
hookIpAddresses =
      Object.fieldDecoder "hookIpAddresses" [] (Decode.string |> Decode.list |> Decode.nullable)


{-| IP addresses that the importer connects from
-}
importerIpAddresses : Field (Maybe (List String)) Github.Object.GitHubMetadata
importerIpAddresses =
      Object.fieldDecoder "importerIpAddresses" [] (Decode.string |> Decode.list |> Decode.nullable)


{-| Whether or not users are verified
-}
isPasswordAuthenticationVerifiable : Field Bool Github.Object.GitHubMetadata
isPasswordAuthenticationVerifiable =
      Object.fieldDecoder "isPasswordAuthenticationVerifiable" [] (Decode.bool)


{-| IP addresses for GitHub Pages' A records
-}
pagesIpAddresses : Field (Maybe (List String)) Github.Object.GitHubMetadata
pagesIpAddresses =
      Object.fieldDecoder "pagesIpAddresses" [] (Decode.string |> Decode.list |> Decode.nullable)
