-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Github.Enum.TeamMemberOrderField exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| Properties by which team member connections can be ordered.

  - Login - Order team members by login
  - CreatedAt - Order team members by creation time

-}
type TeamMemberOrderField
    = Login
    | CreatedAt


decoder : Decoder TeamMemberOrderField
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "LOGIN" ->
                        Decode.succeed Login

                    "CREATED_AT" ->
                        Decode.succeed CreatedAt

                    _ ->
                        Decode.fail ("Invalid TeamMemberOrderField type, " ++ string ++ " try re-running the graphqelm CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : TeamMemberOrderField -> String
toString enum =
    case enum of
        Login ->
            "LOGIN"

        CreatedAt ->
            "CREATED_AT"
